apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: nonvoting
spec:
  #platform: openshift
  image:
  mongod:
    security:
      enableEncryption: true
  replsets:
  - name: rs0
    affinity:
      antiAffinityTopologyKey: none
    non_voting:
      enabled: true
      size: 3
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 1Gi
    size: 3
  secrets:
    users: some-users
