apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: hostpath
spec:
  image:
  mongod:
    security:
      enableEncryption: true
  replsets:
  - name: rs0
    affinity:
      antiAffinityTopologyKey: none
    volumeSpec:
      hostPath:
        path: /tmp/data-dir
        type: Directory
    size: 3
  secrets:
    users: some-users
