apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: upgrade
spec:
  #platform: openshift
  image:
  imagePullPolicy: Always
  allowUnsafeConfigurations: true
  # backup:
  #   enabled: true
  #   debug: true
  #   restartOnFailure: true
  #   image: perconalab/percona-server-mongodb-operator:master-backup
  #   coordinator:
  #     enableClientsLogging: true
  #     resources:
  #       limits:
  #         cpu: "100m"
  #         memory: "0.2G"
  #       requests:
  #         cpu: "100m"
  #         memory: "0.1G"
  #         storage: "1Gi"
  #     affinity:
  #      antiAffinityTopologyKey: "kubernetes.io/hostname"
  #   storages:
  #    minio:
  #      type: s3
  #      s3:
  #        bucket: operator-testing
  #        credentialsSecret: minio-secret
  #        region: us-east-1
  #        endpointUrl: http://minio-service:9000/
  mongod:
    net:
      hostPort: 0
      port: 27017
    operationProfiling:
      mode: slowOp
      rateLimit: 1
      slowOpThresholdMs: 100
    security:
      redactClientLogData: false
    setParameter:
      ttlMonitorSleepSecs: 60
      wiredTigerConcurrentReadTransactions: 128
      wiredTigerConcurrentWriteTransactions: 128
    storage:
      engine: wiredTiger
      inMemory:
        engineConfig:
          inMemorySizeRatio: 0.9
      mmapv1:
        nsSize: 16
        smallfiles: false
      wiredTiger:
        collectionConfig:
          blockCompressor: snappy
        engineConfig:
          cacheSizeRatio: 0.5
          directoryForIndexes: false
          journalCompressor: snappy
        indexConfig:
          prefixCompression: true
  replsets:
  - name: rs0
    size: 3
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
    podDisruptionBudget:
      maxUnavailable: 1
    expose:
      enabled: false
      exposeType: LoadBalancer
    arbiter:
      enabled: false
      size: 1
      affinity:
       antiAffinityTopologyKey: "kubernetes.io/hostname"
    resources:
      limits:
        cpu: "500m"
        memory: "0.5G"
      requests:
        cpu: "300m"
        memory: "0.5G"
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 3Gi
  secrets:
    users: some-users
