apiVersion: psmdb.percona.com/v1alpha1
kind: PerconaServerMongoDB
metadata:
  name: some-name
spec:
  #platform: openshift
  version: "3.6"
  imagePullPolicy: Always
  secrets:
    key: some-key
    users: some-users
  replsets:
  - name: rs0
    size: 3
    resources:
      limits:
        cpu: "500m"
        memory: "1G"
        storage: "1Gi"
      requests:
        cpu: "100m"
        memory: "0.1G"
  mongod:
    net:
      port: 27017
      hostPort: 0
    security:
      redactClientLogData: false
    setParameter:
      ttlMonitorSleepSecs: 60
      wiredTigerConcurrentReadTransactions: 128
      wiredTigerConcurrentWriteTransactions: 128
    storage:
      engine: wiredTiger
      inMemory:
        engineConfig:
          inMemorySizeRatio: 0.9
      mmapv1:
        nsSize: 16
        smallfiles: false
      wiredTiger:
        engineConfig:
          cacheSizeRatio: 0.5
          directoryForIndexes: false
          journalCompressor: snappy
        collectionConfig:
          blockCompressor: snappy
        indexConfig:
          prefixCompression: true
    operationProfiling:
      mode: slowOp
      slowOpThresholdMs: 100
      rateLimit: 1
    #auditLog:
    #  destination: file
    #  format: BSON
    #  filter: '{}'
  backup:
    enabled: true
    debug: true
    version: 0.3.0
    restartOnFailure: true
    coordinator:
      enableClientsLogging: true
      resources:
        limits:
          cpu: "100m"
          memory: "0.2G"
          storage: "1Gi"
        requests:
          cpu: "100m"
          memory: "0.1G"
        #storageClass: aws-gp2
    storages:
      aws-s3:
        type: s3
        s3:
          credentialsSecret: aws-s3-secret
          region: us-east-1
          bucket: operator-testing
      minio:
        type: s3
        s3:
          credentialsSecret: minio-secret
          region: us-east-1
          bucket: operator-testing
          endpointUrl: http://minio-service:9000/
      gcp-cs:
        type: s3
        s3:
          credentialsSecret: gcp-cs-secret
          region: us-east-1
          bucket: operator-testing
          endpointUrl: https://storage.googleapis.com
    tasks:
    - name: weekly
      enabled: true
      schedule: "0 0 * * 0"
      compressionType: gzip
      storageName: aws-s3
