apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: one-pod
spec:
  platform: kubernetes
  image: perconalab/percona-server-mongodb-operator:master-mongod4.0
  imagePullPolicy: Always
  allowUnsafeConfigurations: true
  secrets:
    users: some-users
  pmm:
    enabled: false
    image: -pmm
    serverHost: monitoring-service
  replsets:
  - name: rs0
    size: 1
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
    podDisruptionBudget:
      maxUnavailable: 1
    expose:
      enabled: false
      exposeType: LoadBalancer
    arbiter:
      enabled: false
      size: 1
      affinity:
       antiAffinityTopologyKey: "kubernetes.io/hostname"
    resources:
      limits:
        cpu: "300m"
        memory: "0.5G"
      requests:
        cpu: "300m"
        memory: "0.5G"
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 3Gi
  mongod:
    net:
      port: 27017
      hostPort: 0
    security:
      redactClientLogData: false
      enableEncryption: false
    setParameter:
      ttlMonitorSleepSecs: 60
      wiredTigerConcurrentReadTransactions: 128
      wiredTigerConcurrentWriteTransactions: 128
    storage:
      engine: wiredTiger
      inMemory:
        engineConfig:
          inMemorySizeRatio: 0.9
      mmapv1:
        nsSize: 16
        smallfiles: false
      wiredTiger:
        engineConfig:
          cacheSizeRatio: 0.5
          directoryForIndexes: false
          journalCompressor: snappy
        collectionConfig:
          blockCompressor: snappy
        indexConfig:
          prefixCompression: true
    operationProfiling:
      mode: slowOp
      slowOpThresholdMs: 100
      rateLimit: 100
  backup:
    enabled: true
    debug: true
    restartOnFailure: true
    image: perconalab/percona-server-mongodb-operator:master-backup
    coordinator:
      enableClientsLogging: true
      resources:
        limits:
          cpu: "100m"
          memory: "0.2G"
        requests:
          cpu: "100m"
          memory: "0.1G"
          storage: "1Gi"
      affinity:
       antiAffinityTopologyKey: "kubernetes.io/hostname"
    storages:
     minio:
       type: s3
       s3:
         bucket: operator-testing
         credentialsSecret: minio-secret
         region: us-east-1
         endpointUrl: http://minio-service:9000/
