apiVersion: v1
kind: Secret
metadata:
  name: my-cluster-name-backup-s3
type: Opaque
data:
  AWS_ACCESS_KEY_ID: cHV0LUFXU19BQ0NFU1NfS0VZX0lELWhlcmU=
  AWS_SECRET_ACCESS_KEY: cHV0LUFXU19TRUNSRVRfQUNDRVNTX0tFWS1oZXJl
