apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongos
  namespace: NAMESPACE_ID
spec:
  replicas: 3
  selector:
    matchLabels:
      role: mongos
      tier: routers
  template:
    metadata:
      labels:
        role: mongos
        tier: routers
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: tier
                  operator: In
                  values:
                  - routers
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongos-container
          image: percona/percona-server-mongodb:4.2.8-8
          args:
            - mongos
            - --bind_ip_all
            - --auth
            - --dbpath=/data/db
            - --port=27017
            - --replSet=cfg0
            - --storageEngine=wiredTiger
            - --relaxPermChecks
            - --sslAllowInvalidCertificates
            - --sslMode=preferSSL
            - --clusterAuthMode=x509
            - --configsvr
            - --slowms=100
            - --profile=1
            - --rateLimit=100
            - --enableEncryption
            - --encryptionKeyFile=/etc/mongodb-encryption/encryption-key
            - --encryptionCipherMode=AES256-CBC
            - --wiredTigerCollectionBlockCompressor=snappy
            - --wiredTigerJournalCompressor=snappy
            - --wiredTigerIndexPrefixCompression=true
            - --setParameter
            - ttlMonitorSleepSecs=60
            - --setParameter
            - wiredTigerConcurrentReadTransactions=128
            - --setParameter
            - wiredTigerConcurrentWriteTransactions=128
            - --configdb
            - "rs0-cfg/mongodb-configdb-0.mongodb-configdb-headless-service.NAMESPACE_ID.svc.cluster.local:27019,mongodb-configdb-1.mongodb-configdb-headless-service.NAMESPACE_ID.svc.cluster.local:27019,mongodb-configdb-2.mongodb-configdb-headless-service.NAMESPACE_ID.svc.cluster.local:27019"
          command:
          - /data/db/ps-entry.sh
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
          ports:
            - containerPort: 27017
  volumes:
  - name: mongod-data
    persistentVolumeClaim:
      claimName: mongod-data-my-cluster-name-cfg0-2
  - name: my-cluster-name-mongodb-keyfile
    secret:
      defaultMode: 288
      optional: false
      secretName: my-cluster-name-mongodb-keyfile
  - name: my-cluster-name-mongodb-encryption-key
    secret:
      defaultMode: 288
      optional: false
      secretName: my-cluster-name-mongodb-encryption-key
  - name: ssl
    secret:
      defaultMode: 288
      optional: false
      secretName: my-cluster-name-ssl
  - name: ssl-internal
    secret:
      defaultMode: 288
      optional: true
      secretName: my-cluster-name-ssl-internal
  - name: default-token-xc6sg
    secret:
      defaultMode: 420
      secretName: default-token-xc6sg
