kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: customresourcedefinition-creator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
      - services
      - endpoints
      - persistentvolumeclaims
      - configmaps
      - secrets
    verbs:
      - "create"
      - "update"
      - "delete"
      - "get"
      - "list"
      - "watch"
      - "patch"
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - "create"
      - "update"
      - "delete"
      - "get"
      - "list"
      - "watch"
      - "patch"
  - apiGroups:
      - apiextensions
    resources:
      - customresourcedefinitions
    verbs:
      - "create"
      - "update"
      - "delete"
      - "get"
      - "list"
      - "watch"
      - "patch"
  - apiGroups:
      - psmdb.percona.com
    resources:
      - perconaservermongodbs
    verbs:
      - "create"
      - "update"
      - "delete"
      - "get"
      - "list"
      - "watch"
      - "patch"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: customresourcedefinition-creator-bindings
subjects:
  - kind: User
    name: PASTE_YOUR_USER_NAME_HERE
roleRef:
  kind: Role
  name: customresourcedefinition-creator
  apiGroup: rbac.authorization.k8s.io