apiVersion: v1
kind: Service
metadata:
  name: some-name-backup-coordinator
  ownerReferences:
  - apiVersion: psmdb.percona.com/v1alpha1
    controller: true
    kind: PerconaServerMongoDB
    name: some-name
spec:
  ports:
  - name: rpc
    port: 10000
    protocol: TCP
    targetPort: 10000
  - name: api
    port: 10001
    protocol: TCP
    targetPort: 10001
  selector:
    app: percona-server-mongodb
    backup-coordinator: "true"
    percona-server-mongodb_cr: some-name
  sessionAffinity: None
  type: ClusterIP
