apiVersion: apps/v1
kind: StatefulSet
metadata:
  generation: 1
  labels:
    app: percona-server-mongodb
    backup-coordinator: "true"
    percona-server-mongodb_cr: some-name
  name: some-name-backup-coordinator
  ownerReferences:
  - apiVersion: psmdb.percona.com/v1alpha1
    controller: true
    kind: PerconaServerMongoDB
    name: some-name
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: percona-server-mongodb
      backup-coordinator: "true"
      percona-server-mongodb_cr: some-name
  serviceName: some-name-backup-coordinator
  template:
    metadata:
      labels:
        app: percona-server-mongodb
        backup-coordinator: "true"
        percona-server-mongodb_cr: some-name
    spec:
      containers:
      - env:
        - name: PBM_COORDINATOR_ENABLE_CLIENTS_LOGGING
          value: "true"
        - name: PBM_COORDINATOR_DEBUG
          value: "true"
        - name: PBM_COORDINATOR_API_PORT
          value: "10001"
        - name: PBM_COORDINATOR_GRPC_PORT
          value: "10000"
        - name: PBM_COORDINATOR_WORK_DIR
          value: /data
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 10000
          timeoutSeconds: 3
        name: backup-coordinator
        ports:
        - containerPort: 10000
          name: rpc
          protocol: TCP
        - containerPort: 10001
          name: api
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 200M
          requests:
            cpu: 100m
            memory: 100M
        securityContext:
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: backup-metadata
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: backup-metadata
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
    status:
      phase: Pending
