apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: some-name-backup-every-min-gcp-cs
  ownerReferences:
  - apiVersion: psmdb.percona.com/v1alpha1
    controller: true
    kind: PerconaServerMongoDB
    name: some-name
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        app: percona-server-mongodb
        percona-server-mongodb_cr: some-name
    spec:
      template:
        metadata:
        spec:
          containers:
          - args:
            - run
            - backup
            - --description=some-name-every-min-gcp-cs
            - --storage=gcp-cs
            - --compression-algorithm=gzip
            env:
            - name: PBMCTL_SERVER_ADDRESS
              value: some-name-backup-coordinator:10001
            imagePullPolicy: Always
            name: backup-pmbctl
            resources: {}
            securityContext:
              runAsNonRoot: true
              runAsUser: 1001
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext:
            fsGroup: 1001
          terminationGracePeriodSeconds: 30
  schedule: '* * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
