apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: local-balancer
spec:
  #platform: openshift
  image:
  replsets:
  - name: rs0
    affinity:
      antiAffinityTopologyKey: none
    expose:
      enabled: true
      exposeType: LoadBalancer
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 1Gi
    size: 3
  secrets:
    users: some-users
