apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: monitoring
spec:
  #platform: openshift
  image:
  mongod:
    operationProfiling:
      mode: all
      rateLimit: 1
  replsets:
  - name: rs0
    affinity:
      antiAffinityTopologyKey: none
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 1Gi
    size: 3
  pmm:
    enabled: true
    image: perconalab/pmm-client:1.17.1
    serverHost: monitoring-service
  secrets:
    users: some-users
